GOOGLE_API_KEY="AIzaSyAjHYoZwQ1x15BD7DJuZNjJyOk2TjVfTN8"
PYTHONPATH=":`pwd`" 
DJANGO_SECRET_KEY='aa' 
DJANGO_SETTINGS_MODULE='delivery_helper.settings.rot_jupiter' 


runserver:
	GOOGLE_API_KEY=$(GOOGLE_API_KEY) PYTHONPATH=$(PYTHONPATH) DJANGO_SECRET_KEY=$(DJANGO_SECRET_KEY) DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE) python delivery_helper/manage.py runserver

shell:
	GOOGLE_API_KEY=$(GOOGLE_API_KEY) PYTHONPATH=$(PYTHONPATH) DJANGO_SECRET_KEY=$(DJANGO_SECRET_KEY) DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE) python delivery_helper/manage.py shell

createsuperuser:
	GOOGLE_API_KEY=$(GOOGLE_API_KEY) PYTHONPATH=$(PYTHONPATH) DJANGO_SECRET_KEY=$(DJANGO_SECRET_KEY) DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE) python delivery_helper/manage.py createsuperuser

migrate:
	GOOGLE_API_KEY=$(GOOGLE_API_KEY) PYTHONPATH=$(PYTHONPATH) DJANGO_SECRET_KEY=$(DJANGO_SECRET_KEY) DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE) python delivery_helper/manage.py makemigrations  && \
	GOOGLE_API_KEY=$(GOOGLE_API_KEY) PYTHONPATH=$(PYTHONPATH) DJANGO_SECRET_KEY=$(DJANGO_SECRET_KEY) DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE) python delivery_helper/manage.py migrate
